def line():#
    primcoef = (float(input("Ingrese el coeficiente A: ")))
    segcoef = (float(input("Ingrese el coeficiente B: ")))
    xcoef = (float(input("Ingrese el coeficiente X1: ")))
    x2coef = (float(input("Ingrese el coeficiente X2: ")))
    ec1 = (primcoef*xcoef + segcoef)
    ec2 = (primcoef*x2coef + segcoef)
    print(f"El coeficiente A de su ecuación de la recta es: {primcoef}")
    print(f"El coeficiente B de su ecuación de la recta es: {segcoef}")
    print(f"El coeficiente X1 de su ecuación de la recta es: {xcoef}")
    print(f"El coeficiente X2 de su ecuación de la recta es: {x2coef}")
    ecuacion =  (f"\n\tY = {primcoef}X + {segcoef}")
    print("")
    print(f"Para la siguiente ecuación:{ecuacion}")
    print("")
    puntos = (f"P1 ({xcoef}, {ec1})")
    puntitos = (f"P2 ({x2coef}, {ec2})")
    print(f"Dados los siguientes puntos:\n\t{puntos}")
    print(f"\t{puntitos}")
    d = (((x2coef - xcoef)**2 + (ec2 - ec1)**2)**0.5)
    print(f"\nLa distancia entre ellos es: {d}")
